print (r'    /\ ')
print (r'   /  \ ')
print (r'  /    \ ')
print (r' /      \ ')
print (r'/________\ ')
print (r' ')
print (r'__________')
print (r'!        !')
print (r'!        !')
print (r'!        !')
print (r'----------')
print (r' ')
print (r'  \     /')
print (r'   \   /')
print (r'    \ /')
print (r'     X')
print (r'     /\ ')
print (r'    /  \ ')
print (r'   /    \ ')
